In [0]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pickle

In [0]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import SGDClassifier

from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

from sklearn.metrics import roc_curve

In [0]:
import keras
from keras import models
from keras import layers

from keras.utils import to_categorical

In [0]:
from sklearn.neural_network import MLPClassifier

In [0]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive


In [0]:
df = pd.read_csv('/content/drive/My Drive/Colab/thesis/celeba/celeba_merged_embedding_attributes.csv')

In [0]:
emb = np.load('/content/drive/My Drive/Colab/thesis/celeba/celeb_emb_npy.npy')

In [0]:
emb.shape

(201498, 128)

In [0]:
df.shape

(201498, 12)

In [0]:
df.head(10)

encodings        file  Male  \
0  [-0.10657232  0.12290111  0.06805265 -0.041072...  000001.jpg     0   
1  [-0.11027038  0.02495586  0.05625371 -0.070694...  000002.jpg     0   
2  [-0.12229778  0.20610951  0.05414608 -0.035753...  000003.jpg     1   
3  [-1.84543923e-01  1.76940337e-01  1.39256537e-...  000004.jpg     0   
4  [-0.08415149  0.0511583   0.01261529 -0.051950...  000005.jpg     0   
5  [-0.01535916 -0.00451871  0.01638835  0.017832...  000006.jpg     0   
6  [-1.45129263e-01  6.18378632e-02  6.61352053e-...  000007.jpg     1   
7  [ 0.02644151  0.15732542 -0.0238539   0.008128...  000008.jpg     1   
8  [-0.14153117  0.04991306  0.09734342 -0.129968...  000009.jpg     0   
9  [-0.09212744  0.14240824 -0.02830539 -0.158743...  000010.jpg     0   

   Black_Hair  Blond_Hair  Brown_Hair  Bald  Eyeglasses  Mustache  No_Beard  \
0           0           0           1     0           0         0         1   
1           0           0           1     0           0         0         1   
2           0           0           0     0           0         0         1   
3           0           0           0     0           0         0         1   
4           0           0           0     0           0         0         1   
5           0           0           1     0           0         0         1   
6           1           0           0     0           0         0         1   
7           1           0           0     0           0         0         1   
8           0           0           0     0           0         0         1   
9           0           0           0     0           0         0         1   

   Goatee  5_o_Clock_Shadow  
0       0                 0  
1       0                 0  
2       0                 0  
3       0                 0  
4       0                 0  
5       0                 0  
6       0                 1  
7       0                 1  
8       0                 0  
9       0                 0

In [0]:
df.Male.value_counts()

0    117723
1     83775
Name: Male, dtype: int64

In [0]:
df.Male[:20000].value_counts()

0    11589
1     8411
Name: Male, dtype: int64

In [0]:
male = df.Male.values
male

array([0, 0, 1, ..., 1, 0, 0])

In [0]:
#test with small subset
male_sub = male[:20000]
emb_sub = emb[:20000]

In [0]:
emb_sub.shape

(20000, 128)

In [0]:
#subset
X_train,X_test,y_train,y_test = train_test_split(emb_sub, male_sub,test_size=0.25,random_state=91, stratify=male_sub)

In [0]:
print('train')
print(X_train.shape)
print(y_train.shape)

print('test')
print(X_test.shape)
print(y_test.shape)


train
(15000, 128)
(15000,)
test
(5000, 128)
(5000,)


In [0]:
model = SGDClassifier(loss='log', random_state=91, max_iter=5)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print("{:.3}".format(accuracy_score(y_test, y_pred)))

print(classification_report(y_test,y_pred))

print(confusion_matrix(y_test,y_pred))

0.984
              precision    recall  f1-score   support

           0       0.98      0.99      0.99      2897
           1       0.99      0.98      0.98      2103

   micro avg       0.98      0.98      0.98      5000
   macro avg       0.98      0.98      0.98      5000
weighted avg       0.98      0.98      0.98      5000

[[2870   27]
 [  51 2052]]


/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If max_iter is set but tol is left unset, the default value for tol in 0.19 and 0.20 will be None (which is equivalent to -infinity, so it has no effect) but will change in 0.21 to 1e-3. Specify tol to silence this warning.
  FutureWarning)


In [0]:
model = SGDClassifier(loss='hinge', random_state=91, max_iter=5)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print("{:.3}".format(accuracy_score(y_test, y_pred)))

print(classification_report(y_test,y_pred))

print(confusion_matrix(y_test,y_pred))

0.984
              precision    recall  f1-score   support

           0       0.98      0.99      0.99      2897
           1       0.99      0.97      0.98      2103

   micro avg       0.98      0.98      0.98      5000
   macro avg       0.98      0.98      0.98      5000
weighted avg       0.98      0.98      0.98      5000

[[2874   23]
 [  58 2045]]


/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If max_iter is set but tol is left unset, the default value for tol in 0.19 and 0.20 will be None (which is equivalent to -infinity, so it has no effect) but will change in 0.21 to 1e-3. Specify tol to silence this warning.
  FutureWarning)


In [0]:
#full dataset
X_train,X_test,y_train,y_test = train_test_split(emb, male,test_size=0.25,random_state=91, stratify=male)

print('train')
print(X_train.shape)
print(y_train.shape)

print('test')
print(X_test.shape)
print(y_test.shape)


train
(151123, 128)
(151123,)
test
(50375, 128)
(50375,)


In [0]:
model = SGDClassifier(loss='log', random_state=91, max_iter=40)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print("{:.3}".format(accuracy_score(y_test, y_pred)))

print(classification_report(y_test,y_pred))

print(confusion_matrix(y_test,y_pred))

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If max_iter is set but tol is left unset, the default value for tol in 0.19 and 0.20 will be None (which is equivalent to -infinity, so it has no effect) but will change in 0.21 to 1e-3. Specify tol to silence this warning.
  FutureWarning)


0.984
              precision    recall  f1-score   support

           0       0.98      0.99      0.99     29431
           1       0.98      0.98      0.98     20944

   micro avg       0.98      0.98      0.98     50375
   macro avg       0.98      0.98      0.98     50375
weighted avg       0.98      0.98      0.98     50375

[[29089   342]
 [  476 20468]]


In [0]:
# save the model to disk
filename = 'gender_model.sav'
pickle.dump(model, open(filename, 'wb'))

In [0]:
model = SGDClassifier(loss='hinge', random_state=91, max_iter=5)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print("{:.3}".format(accuracy_score(y_test, y_pred)))

print(classification_report(y_test,y_pred))

print(confusion_matrix(y_test,y_pred))

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If max_iter is set but tol is left unset, the default value for tol in 0.19 and 0.20 will be None (which is equivalent to -infinity, so it has no effect) but will change in 0.21 to 1e-3. Specify tol to silence this warning.
  FutureWarning)


0.984
              precision    recall  f1-score   support

           0       0.98      0.99      0.99     29431
           1       0.99      0.98      0.98     20944

   micro avg       0.98      0.98      0.98     50375
   macro avg       0.98      0.98      0.98     50375
weighted avg       0.98      0.98      0.98     50375

[[29131   300]
 [  515 20429]]


In [0]:
model = SGDClassifier(loss='perceptron', random_state=91, max_iter=6)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print("{:.3}".format(accuracy_score(y_test, y_pred)))

print(classification_report(y_test,y_pred))

print(confusion_matrix(y_test,y_pred))

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If max_iter is set but tol is left unset, the default value for tol in 0.19 and 0.20 will be None (which is equivalent to -infinity, so it has no effect) but will change in 0.21 to 1e-3. Specify tol to silence this warning.
  FutureWarning)


0.984
              precision    recall  f1-score   support

           0       0.98      0.99      0.99     29431
           1       0.98      0.98      0.98     20944

   micro avg       0.98      0.98      0.98     50375
   macro avg       0.98      0.98      0.98     50375
weighted avg       0.98      0.98      0.98     50375

[[29097   334]
 [  469 20475]]


In [0]:
clf = MLPClassifier(solver='adam', hidden_layer_sizes=(128, 128),max_iter = 40, verbose=True, tol=1e-4, activation='tanh')
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
score = clf.predict_proba(X_test)

print("{:.3}".format(accuracy_score(y_test, y_pred)))
print(classification_report(y_test,y_pred))

print(confusion_matrix(y_test,y_pred))

Iteration 1, loss = 0.07176806
Iteration 2, loss = 0.05453825
Iteration 3, loss = 0.05372543
Iteration 4, loss = 0.05402774
Iteration 5, loss = 0.05342143
Iteration 6, loss = 0.05276486
Iteration 7, loss = 0.05208719
Iteration 8, loss = 0.05176349
Iteration 9, loss = 0.05137487
Iteration 10, loss = 0.05106549
Iteration 11, loss = 0.05055762


/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/multilayer_perceptron.py:564: UserWarning: Training interrupted by user.
  warnings.warn("Training interrupted by user.")


0.984
              precision    recall  f1-score   support

           0       0.98      0.99      0.99     29431
           1       0.98      0.98      0.98     20944

   micro avg       0.98      0.98      0.98     50375
   macro avg       0.98      0.98      0.98     50375
weighted avg       0.98      0.98      0.98     50375

[[29118   313]
 [  477 20467]]


In [0]:


#optimizers.RMSprop(lr=1e-4)

hidden = 100

network = models.Sequential()
network.add(layers.Dense(hidden, use_bias='true', activation='relu', input_shape=(128,)))
network.add(layers.Dense(1, use_bias='true', activation='sigmoid'))

keras.initializers.RandomNormal(mean=0.0, stddev=0.05)

#keras.optimizers.SGD(lr=0.001, momentum=0.0, decay=0.0, nesterov=False)

network.compile(optimizer=keras.optimizers.Adam(lr=0.001, beta_1=0.9, beta_2=0.999, epsilon=None, decay=0.0, amsgrad=False),
                loss='binary_crossentropy',
                metrics=['accuracy'])

network.fit(X_train, y_train, epochs=30, batch_size=50)

Epoch 1/30
151123/151123 [==============================] - 13s 88us/step - loss: 0.0689 - acc: 0.9803
Epoch 2/30
151123/151123 [==============================] - 12s 83us/step - loss: 0.0538 - acc: 0.9849
Epoch 3/30
151123/151123 [==============================] - 12s 82us/step - loss: 0.0526 - acc: 0.9852
Epoch 4/30
151123/151123 [==============================] - 12s 82us/step - loss: 0.0514 - acc: 0.9852
Epoch 5/30
151123/151123 [==============================] - 12s 83us/step - loss: 0.0502 - acc: 0.9856
Epoch 6/30
151123/151123 [==============================] - 12s 82us/step - loss: 0.0490 - acc: 0.9859
Epoch 7/30
151123/151123 [==============================] - 12s 82us/step - loss: 0.0482 - acc: 0.9860
Epoch 8/30
151123/151123 [==============================] - 12s 82us/step - loss: 0.0473 - acc: 0.9861
Epoch 9/30
151123/151123 [==============================] - 12s 82us/step - loss: 0.0464 - acc: 0.9866
Epoch 10/30
151123/151123 [==============================] - 12s 83us/ste

In [0]:
y_pred = network.predict(X_test)
y_pred = (y_pred > 0.5)
#score = network.predict_proba(X_test)

print("{:.3}".format(accuracy_score(y_test, y_pred)))
print(classification_report(y_test,y_pred))

print(confusion_matrix(y_test,y_pred))

0.986
              precision    recall  f1-score   support

           0       0.99      0.99      0.99     29431
           1       0.99      0.98      0.98     20944

   micro avg       0.99      0.99      0.99     50375
   macro avg       0.99      0.99      0.99     50375
weighted avg       0.99      0.99      0.99     50375

[[29170   261]
 [  434 20510]]


In [0]:
filename = 'gender_keras_model.sav'
pickle.dump(network, open(filename, 'wb'))

# glasses

In [0]:
df.Eyeglasses.value_counts()

0    188449
1     13049
Name: Eyeglasses, dtype: int64

In [0]:
glas = df.Eyeglasses.values

In [0]:
glas

array([0, 0, 0, ..., 1, 1, 1])

In [0]:
X_train,X_test,y_train,y_test = train_test_split(emb, glas,test_size=0.25,random_state=91, stratify=glas)

print('train')
print(X_train.shape)
print(y_train.shape)

print('test')
print(X_test.shape)
print(y_test.shape)


train
(151123, 128)
(151123,)
test
(50375, 128)
(50375,)


In [0]:
model = SGDClassifier(loss='log', random_state=91, max_iter=5)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print("{:.3}".format(accuracy_score(y_test, y_pred)))

print(classification_report(y_test,y_pred))

print(confusion_matrix(y_test,y_pred))

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If max_iter is set but tol is left unset, the default value for tol in 0.19 and 0.20 will be None (which is equivalent to -infinity, so it has no effect) but will change in 0.21 to 1e-3. Specify tol to silence this warning.
  FutureWarning)


0.951
              precision    recall  f1-score   support

           0       0.95      1.00      0.97     47113
           1       0.93      0.27      0.42      3262

   micro avg       0.95      0.95      0.95     50375
   macro avg       0.94      0.63      0.70     50375
weighted avg       0.95      0.95      0.94     50375

[[47051    62]
 [ 2382   880]]


In [0]:
model = SGDClassifier(loss='hinge', random_state=91, max_iter=40)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print("{:.3}".format(accuracy_score(y_test, y_pred)))

print(classification_report(y_test,y_pred))

print(confusion_matrix(y_test,y_pred))

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If max_iter is set but tol is left unset, the default value for tol in 0.19 and 0.20 will be None (which is equivalent to -infinity, so it has no effect) but will change in 0.21 to 1e-3. Specify tol to silence this warning.
  FutureWarning)


0.955
              precision    recall  f1-score   support

           0       0.95      1.00      0.98     47113
           1       0.96      0.31      0.47      3262

   micro avg       0.95      0.95      0.95     50375
   macro avg       0.96      0.66      0.72     50375
weighted avg       0.96      0.95      0.94     50375

[[47075    38]
 [ 2241  1021]]


In [0]:
filename = 'glasses_model.sav'
pickle.dump(model, open(filename, 'wb'))

In [0]:
clf = MLPClassifier(solver='adam', hidden_layer_sizes=(128, 128),max_iter = 25, verbose=True, tol=1e-4, activation='relu')
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
score = clf.predict_proba(X_test)

print("{:.3}".format(accuracy_score(y_test, y_pred)))
print(classification_report(y_test,y_pred))

print(confusion_matrix(y_test,y_pred))

Iteration 1, loss = 0.15866756
Iteration 2, loss = 0.09410872
Iteration 3, loss = 0.06852118
Iteration 4, loss = 0.05879127
Iteration 5, loss = 0.05197428
Iteration 6, loss = 0.04708383
Iteration 7, loss = 0.04490795
Iteration 8, loss = 0.04204692
Iteration 9, loss = 0.03975551
Iteration 10, loss = 0.03826528
Iteration 11, loss = 0.03690978
Iteration 12, loss = 0.03588126
Iteration 13, loss = 0.03438935
Iteration 14, loss = 0.03446756
Iteration 15, loss = 0.03291528
Iteration 16, loss = 0.03197527
Iteration 17, loss = 0.03113957
Iteration 18, loss = 0.03055257
Iteration 19, loss = 0.02936187
Iteration 20, loss = 0.03018748
Iteration 21, loss = 0.02829025
Iteration 22, loss = 0.02807101
Iteration 23, loss = 0.02762381
Iteration 24, loss = 0.02690086
Iteration 25, loss = 0.02684036


/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/multilayer_perceptron.py:562: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (25) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


0.986
              precision    recall  f1-score   support

           0       0.99      0.99      0.99     47113
           1       0.91      0.87      0.89      3262

   micro avg       0.99      0.99      0.99     50375
   macro avg       0.95      0.93      0.94     50375
weighted avg       0.99      0.99      0.99     50375

[[46840   273]
 [  408  2854]]


In [0]:
filename = 'glasses_mlp_model.sav'
pickle.dump(clf, open(filename, 'wb'))

In [0]:
train_labels = to_categorical(y_train)
test_labels = to_categorical(y_test)

In [0]:


#optimizers.RMSprop(lr=1e-4)

hidden = 128

network = models.Sequential()
network.add(layers.Dense(hidden, use_bias='true', activation='relu', input_shape=(128,)))
network.add(layers.Dense(1, use_bias='true', activation='sigmoid'))

keras.initializers.RandomNormal(mean=0.0, stddev=0.05)

#keras.optimizers.SGD(lr=0.001, momentum=0.0, decay=0.0, nesterov=False)

network.compile(optimizer=keras.optimizers.Adam(lr=0.001, beta_1=0.9, beta_2=0.999, epsilon=None, decay=0.0, amsgrad=False),
                loss='binary_crossentropy',
                metrics=['accuracy'])

network.fit(X_train, y_train, epochs=30, batch_size=50)

Epoch 1/30
151123/151123 [==============================] - 12s 82us/step - loss: 0.1579 - acc: 0.9502
Epoch 2/30
151123/151123 [==============================] - 12s 82us/step - loss: 0.1296 - acc: 0.9600
Epoch 3/30
151123/151123 [==============================] - 12s 82us/step - loss: 0.1148 - acc: 0.9632
Epoch 4/30
151123/151123 [==============================] - 12s 82us/step - loss: 0.0999 - acc: 0.9663
Epoch 5/30
151123/151123 [==============================] - 12s 82us/step - loss: 0.0866 - acc: 0.9697
Epoch 6/30
151123/151123 [==============================] - 12s 82us/step - loss: 0.0767 - acc: 0.9736
Epoch 7/30
151123/151123 [==============================] - 12s 82us/step - loss: 0.0691 - acc: 0.9759
Epoch 8/30
151123/151123 [==============================] - 12s 81us/step - loss: 0.0635 - acc: 0.9781
Epoch 9/30
151123/151123 [==============================] - 12s 82us/step - loss: 0.0584 - acc: 0.9800
Epoch 10/30
151123/151123 [==============================] - 12s 81us/ste

In [0]:
test_loss, test_acc = network.evaluate(X_test, y_test)
print('test_acc:', test_acc, '             test_loss:', format(round(test_loss,4)))

50375/50375 [==============================] - 2s 47us/step
test_acc: 0.985727047146402              test_loss: 0.0444


In [0]:
y_pred = network.predict(X_test)
y_pred = (y_pred > 0.5)
#score = network.predict_proba(X_test)

print("{:.3}".format(accuracy_score(y_test, y_pred)))
print(classification_report(y_test,y_pred))

print(confusion_matrix(y_test,y_pred))

0.986
              precision    recall  f1-score   support

           0       0.99      0.99      0.99     47113
           1       0.89      0.89      0.89      3262

   micro avg       0.99      0.99      0.99     50375
   macro avg       0.94      0.94      0.94     50375
weighted avg       0.99      0.99      0.99     50375

[[46768   345]
 [  374  2888]]


In [0]:
filename = 'glasses_keras_model.sav'
pickle.dump(network, open(filename, 'wb'))

# Glasses balanced


## undersample

In [0]:
glas_under = pd.read_csv('/content/drive/My Drive/Colab/thesis/celeba/celeba_glasses_undersample.csv')

In [0]:
glas_under.head()

encodings        file  Eyeglasses
0  [-0.18005028  0.16697682  0.05575646 -0.046464...  009373.jpg           0
1  [-0.0319382  -0.01829863  0.04162911  0.043951...  072815.jpg           0
2  [-7.29213655e-02  1.29021764e-01  3.57191749e-...  156208.jpg           0
3  [-1.86423451e-01  2.16368176e-02  2.33115405e-...  087508.jpg           0
4  [-0.13597131  0.09287494  0.08348855 -0.114260...  129633.jpg           0

In [0]:
glas = glas_under.Eyeglasses.values

In [0]:
emb = glas_under.encodings

In [0]:
emb = (emb
 .str.replace('\n','')
 .str.replace('\r','')
 .str.replace('[','')
 .str.replace(']','')
 .str.split())

In [0]:
emb_lists = emb.tolist()
glas_under_emb_npy = np.asarray(emb_lists)
glas_under_emb_npy = glas_under_emb_npy.astype(np.float)

In [0]:
glas_under_emb_npy.shape

(26098, 128)

In [0]:
X_train,X_test,y_train,y_test = train_test_split(glas_under_emb_npy, glas,test_size=0.25,random_state=91)

print('train')
print(X_train.shape)
print(y_train.shape)

print('test')
print(X_test.shape)
print(y_test.shape)

train
(19573, 128)
(19573,)
test
(6525, 128)
(6525,)


In [0]:
y_train

array([0, 0, 0, ..., 0, 0, 0])

In [0]:
unique, counts = np.unique(y_train, return_counts=True)
print(np.asarray((unique, counts)).T)

[[   0 9808]
 [   1 9765]]


In [0]:
model = SGDClassifier(loss='log', random_state=91, max_iter=30)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print("{:.3}".format(accuracy_score(y_test, y_pred)))

print(classification_report(y_test,y_pred))

print(confusion_matrix(y_test,y_pred))

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If max_iter is set but tol is left unset, the default value for tol in 0.19 and 0.20 will be None (which is equivalent to -infinity, so it has no effect) but will change in 0.21 to 1e-3. Specify tol to silence this warning.
  FutureWarning)


0.822
              precision    recall  f1-score   support

           0       0.81      0.84      0.83      3241
           1       0.84      0.80      0.82      3284

   micro avg       0.82      0.82      0.82      6525
   macro avg       0.82      0.82      0.82      6525
weighted avg       0.82      0.82      0.82      6525

[[2734  507]
 [ 652 2632]]


In [0]:
filename = 'glasses_undersample_model.sav'
pickle.dump(model, open(filename, 'wb'))

In [0]:
model = SGDClassifier(loss='hinge', random_state=91, max_iter=40)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print("{:.3}".format(accuracy_score(y_test, y_pred)))

print(classification_report(y_test,y_pred))

print(confusion_matrix(y_test,y_pred))

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If max_iter is set but tol is left unset, the default value for tol in 0.19 and 0.20 will be None (which is equivalent to -infinity, so it has no effect) but will change in 0.21 to 1e-3. Specify tol to silence this warning.
  FutureWarning)


0.826
              precision    recall  f1-score   support

           0       0.80      0.87      0.83      3241
           1       0.86      0.79      0.82      3284

   micro avg       0.83      0.83      0.83      6525
   macro avg       0.83      0.83      0.83      6525
weighted avg       0.83      0.83      0.83      6525

[[2805  436]
 [ 701 2583]]


In [0]:
clf = MLPClassifier(solver='adam', hidden_layer_sizes=(128, 128),max_iter = 100, verbose=True, tol=1e-4, activation='relu')
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
score = clf.predict_proba(X_test)

print("{:.3}".format(accuracy_score(y_test, y_pred)))
print(classification_report(y_test,y_pred))

print(confusion_matrix(y_test,y_pred))

Iteration 1, loss = 0.53424794
Iteration 2, loss = 0.39857400
Iteration 3, loss = 0.35239553
Iteration 4, loss = 0.31540660
Iteration 5, loss = 0.27570451
Iteration 6, loss = 0.23779965
Iteration 7, loss = 0.21155538
Iteration 8, loss = 0.18817204
Iteration 9, loss = 0.16938368
Iteration 10, loss = 0.15764286
Iteration 11, loss = 0.14918152
Iteration 12, loss = 0.13816624
Iteration 13, loss = 0.12617975
Iteration 14, loss = 0.12366871
Iteration 15, loss = 0.11910825
Iteration 16, loss = 0.11317809
Iteration 17, loss = 0.10422210
Iteration 18, loss = 0.10059747
Iteration 19, loss = 0.10478558
Iteration 20, loss = 0.09508409
Iteration 21, loss = 0.09457967
Iteration 22, loss = 0.09108568
Iteration 23, loss = 0.09271219
Iteration 24, loss = 0.08356225
Iteration 25, loss = 0.08076858
Iteration 26, loss = 0.07688617
Iteration 27, loss = 0.08057987
Iteration 28, loss = 0.07956205
Iteration 29, loss = 0.07230805
Iteration 30, loss = 0.07014070
Iteration 31, loss = 0.06512222
Iteration 32, los

/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/multilayer_perceptron.py:562: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


In [0]:
filename = 'glasses_mlp_undersample_model.sav'
pickle.dump(clf, open(filename, 'wb'))

## oversample

In [0]:
glas_over = pd.read_csv('/content/drive/My Drive/Colab/thesis/celeba/celeba_glasses_oversample.csv')

In [0]:
glas = glas_over.Eyeglasses.values

In [0]:
emb = glas_over.encodings

emb = (emb
 .str.replace('\n','')
 .str.replace('\r','')
 .str.replace('[','')
 .str.replace(']','')
 .str.split())

emb_lists = emb.tolist()
glasover_emb_npy = np.asarray(emb_lists)
glasover_emb_npy = glasover_emb_npy.astype(np.float)


In [0]:
X_train,X_test,y_train,y_test = train_test_split(glasover_emb_npy, glas,test_size=0.25,random_state=91)

print('train')
print(X_train.shape)
print(y_train.shape)

print('test')
print(X_test.shape)
print(y_test.shape)

train
(282673, 128)
(282673,)
test
(94225, 128)
(94225,)


In [0]:
model = SGDClassifier(loss='log', random_state=91, max_iter=30)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print("{:.3}".format(accuracy_score(y_test, y_pred)))

print(classification_report(y_test,y_pred))

print(confusion_matrix(y_test,y_pred))

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If max_iter is set but tol is left unset, the default value for tol in 0.19 and 0.20 will be None (which is equivalent to -infinity, so it has no effect) but will change in 0.21 to 1e-3. Specify tol to silence this warning.
  FutureWarning)


0.832
              precision    recall  f1-score   support

           0       0.81      0.87      0.84     47089
           1       0.86      0.80      0.83     47136

   micro avg       0.83      0.83      0.83     94225
   macro avg       0.83      0.83      0.83     94225
weighted avg       0.83      0.83      0.83     94225

[[40847  6242]
 [ 9626 37510]]


In [0]:
model = SGDClassifier(loss='hinge', random_state=91, max_iter=40)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print("{:.3}".format(accuracy_score(y_test, y_pred)))

print(classification_report(y_test,y_pred))

print(confusion_matrix(y_test,y_pred))

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If max_iter is set but tol is left unset, the default value for tol in 0.19 and 0.20 will be None (which is equivalent to -infinity, so it has no effect) but will change in 0.21 to 1e-3. Specify tol to silence this warning.
  FutureWarning)


0.836
              precision    recall  f1-score   support

           0       0.82      0.86      0.84     47089
           1       0.86      0.81      0.83     47136

   micro avg       0.84      0.84      0.84     94225
   macro avg       0.84      0.84      0.84     94225
weighted avg       0.84      0.84      0.84     94225

[[40638  6451]
 [ 8995 38141]]


In [0]:
filename = 'glasses_oversample_model.sav'
pickle.dump(model, open(filename, 'wb'))

# hair

In [0]:
hairdf = pd.read_csv('/content/drive/My Drive/Colab/thesis/celeba/celeba_hair_dataset.csv')

In [0]:
hairdf.head()

encodings        file  Black_Hair  \
0  [-0.10657232  0.12290111  0.06805265 -0.041072...  000001.jpg           0   
1  [-0.11027038  0.02495586  0.05625371 -0.070694...  000002.jpg           0   
2  [-0.01535916 -0.00451871  0.01638835  0.017832...  000006.jpg           0   
3  [-1.45129263e-01  6.18378632e-02  6.61352053e-...  000007.jpg           1   
4  [ 0.02644151  0.15732542 -0.0238539   0.008128...  000008.jpg           1   

   Blond_Hair  Brown_Hair  Bald  score  color  
0           0           1     0     10  brown  
1           0           1     0     10  brown  
2           0           1     0     10  brown  
3           0           0     0   1000  black  
4           0           0     0   1000  black

In [0]:
color = hairdf.color.values

In [0]:
color.shape


(119257,)

In [0]:
emb = hairdf.encodings

emb = (emb
 .str.replace('\n','')
 .str.replace('\r','')
 .str.replace('[','')
 .str.replace(']','')
 .str.split())

emb_lists = emb.tolist()
hair_emb_npy = np.asarray(emb_lists)
hair_emb_npy = hair_emb_npy.astype(np.float)

In [0]:
hair_emb_npy.shape

(119257, 128)

In [0]:
hair_emb_npy[0]

array([-0.10657232,  0.12290111,  0.06805265, -0.04107244, -0.09091284,
        0.05011651, -0.07214841, -0.11483932,  0.21993797, -0.1022972 ,
        0.27614293, -0.08339494, -0.3679857 ,  0.08410606, -0.08547532,
        0.19960549, -0.26343495, -0.13145217, -0.12658648, -0.08161977,
       -0.03662762, -0.0309852 ,  0.05915862,  0.11871034, -0.21404645,
       -0.38162723, -0.01394539, -0.06993285, -0.03561937, -0.22256935,
        0.02732605,  0.07517888, -0.15110423,  0.1061596 , -0.00903846,
        0.1294672 , -0.01675487, -0.17476815,  0.20844407, -0.03255181,
       -0.22278222, -0.10950559,  0.08133389,  0.29120237,  0.26651287,
       -0.11200815,  0.01510113, -0.07966056,  0.15839767, -0.33412927,
        0.01687353,  0.17194498,  0.05552776,  0.10473292,  0.15672114,
       -0.1223305 , -0.00978362,  0.17710154, -0.09993096, -0.02218643,
        0.10385877, -0.00371413,  0.05319744, -0.11833096,  0.27340212,
        0.1250774 , -0.21254879, -0.11757348,  0.10648198, -0.15

In [0]:
X_train,X_test,y_train,y_test = train_test_split(hair_emb_npy, color,test_size=0.25,random_state=91)

print('train')
print(X_train.shape)
print(y_train.shape)

print('test')
print(X_test.shape)
print(y_test.shape)

train
(89442, 128)
(89442,)
test
(29815, 128)
(29815,)


In [0]:
unique, counts = np.unique(y_train, return_counts=True)
print(np.asarray((unique, counts)).T)

[['bald' 3344]
 ['black' 35404]
 ['blond' 21475]
 ['brown' 29219]]


In [0]:
X_train,X_test,y_train,y_test = train_test_split(hair_emb_npy, color,test_size=0.25,random_state=91, stratify=color)

print('train')
print(X_train.shape)
print(y_train.shape)

print('test')
print(X_test.shape)
print(y_test.shape)

unique, counts = np.unique(y_train, return_counts=True)
print(np.asarray((unique, counts)).T)

train
(89442, 128)
(89442,)
test
(29815, 128)
(29815,)
[['bald' 3338]
 ['black' 35292]
 ['blond' 21498]
 ['brown' 29314]]


In [0]:
model = SGDClassifier(loss='log', random_state=91, max_iter=30)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print("{:.3}".format(accuracy_score(y_test, y_pred)))

print(classification_report(y_test,y_pred))

print(confusion_matrix(y_test,y_pred))

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If max_iter is set but tol is left unset, the default value for tol in 0.19 and 0.20 will be None (which is equivalent to -infinity, so it has no effect) but will change in 0.21 to 1e-3. Specify tol to silence this warning.
  FutureWarning)


0.771
              precision    recall  f1-score   support

        bald       0.80      0.51      0.62      1113
       black       0.75      0.86      0.80     11764
       blond       0.85      0.90      0.87      7166
       brown       0.72      0.61      0.66      9772

   micro avg       0.77      0.77      0.77     29815
   macro avg       0.78      0.72      0.74     29815
weighted avg       0.77      0.77      0.77     29815

[[  568   426    32    87]
 [   46 10082    66  1570]
 [   32   104  6437   593]
 [   66  2751  1040  5915]]


In [0]:
model = SGDClassifier(loss='hinge', random_state=91, max_iter=100)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print("{:.3}".format(accuracy_score(y_test, y_pred)))

print(classification_report(y_test,y_pred))

print(confusion_matrix(y_test,y_pred))

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If max_iter is set but tol is left unset, the default value for tol in 0.19 and 0.20 will be None (which is equivalent to -infinity, so it has no effect) but will change in 0.21 to 1e-3. Specify tol to silence this warning.
  FutureWarning)


0.773
              precision    recall  f1-score   support

        bald       0.78      0.55      0.64      1113
       black       0.76      0.85      0.80     11764
       blond       0.85      0.90      0.87      7166
       brown       0.72      0.62      0.67      9772

   micro avg       0.77      0.77      0.77     29815
   macro avg       0.78      0.73      0.75     29815
weighted avg       0.77      0.77      0.77     29815

[[ 609  399   19   86]
 [  52 9972   78 1662]
 [  37   96 6420  613]
 [  83 2571 1066 6052]]


In [0]:
clf = MLPClassifier(solver='adam', hidden_layer_sizes=(128, 128),max_iter = 500, verbose=True, tol=1e-4, activation='relu')
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
score = clf.predict_proba(X_test)

print("{:.3}".format(accuracy_score(y_test, y_pred)))
print(classification_report(y_test,y_pred))

print(confusion_matrix(y_test,y_pred))

#df_pred = pd.DataFrame(pred, columns=df_label.columns, index=Y_test.index)
#df_score = pd.DataFrame(score, columns=df_label.columns, index=Y_test.index)

Iteration 1, loss = 0.62456966
Iteration 2, loss = 0.49296943
Iteration 3, loss = 0.48427027
Iteration 4, loss = 0.47597119
Iteration 5, loss = 0.47031300
Iteration 6, loss = 0.46588894
Iteration 7, loss = 0.46297191
Iteration 8, loss = 0.45766151
Iteration 9, loss = 0.45545569
Iteration 10, loss = 0.45194226
Iteration 11, loss = 0.44928445
Iteration 12, loss = 0.44400922
Iteration 13, loss = 0.44201135
Iteration 14, loss = 0.43864915
Iteration 15, loss = 0.43615118
Iteration 16, loss = 0.43207264
Iteration 17, loss = 0.43020043
Iteration 18, loss = 0.42831061
Iteration 19, loss = 0.42501172
Iteration 20, loss = 0.42261766
Iteration 21, loss = 0.41887230
Iteration 22, loss = 0.41739806
Iteration 23, loss = 0.41473009
Iteration 24, loss = 0.41294700
Iteration 25, loss = 0.41033688
Iteration 26, loss = 0.41024670
Iteration 27, loss = 0.40632242
Iteration 28, loss = 0.40333613
Iteration 29, loss = 0.40226920
Iteration 30, loss = 0.40055790
Iteration 31, loss = 0.39766656
Iteration 32, los

/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/multilayer_perceptron.py:564: UserWarning: Training interrupted by user.
  warnings.warn("Training interrupted by user.")


0.815
              precision    recall  f1-score   support

        bald       0.81      0.80      0.80      1113
       black       0.80      0.89      0.84     11764
       blond       0.87      0.91      0.89      7166
       brown       0.79      0.66      0.72      9772

   micro avg       0.82      0.82      0.82     29815
   macro avg       0.82      0.81      0.81     29815
weighted avg       0.81      0.82      0.81     29815

[[  889   165    18    41]
 [  104 10478    41  1141]
 [   32    53  6519   562]
 [   77  2355   921  6419]]


In [0]:
from sklearn.preprocessing import LabelEncoder
# Fit LabelEncoder with our list of classes
label_encoder = LabelEncoder()
#label_encoder.fit(y_train)
label_encoder.fit(color)

# Encode class values as integers
#y_train = label_encoder.transform(y_train)
color = label_encoder.transform(color)

In [0]:
X_train,X_test,y_train,y_test = train_test_split(hair_emb_npy, color,test_size=0.25,random_state=91, stratify=color)

print('train')
print(X_train.shape)
print(y_train.shape)

print('test')
print(X_test.shape)
print(y_test.shape)

unique, counts = np.unique(y_train, return_counts=True)
print(np.asarray((unique, counts)).T)

train
(89442, 128)
(89442,)
test
(29815, 128)
(29815,)
[[    0  3338]
 [    1 35292]
 [    2 21498]
 [    3 29314]]


In [0]:
y_train = to_categorical(y_train)
y_test = to_categorical(y_test)

#optimizers.RMSprop(lr=1e-4)

hidden = 100

network = models.Sequential()
network.add(layers.Dense(hidden, use_bias='true', activation='relu', input_shape=(128,)))
network.add(layers.Dense(4, use_bias='true', activation='softmax'))

keras.initializers.RandomNormal(mean=0.0, stddev=0.05)

#keras.optimizers.SGD(lr=0.001, momentum=0.0, decay=0.0, nesterov=False)

network.compile(optimizer=keras.optimizers.Adam(lr=0.001, beta_1=0.9, beta_2=0.999, epsilon=None, decay=0.0, amsgrad=False),
                loss='categorical_crossentropy',
                metrics=['accuracy'])

network.fit(X_train, y_train, epochs=30, batch_size=50)

Epoch 1/30
89442/89442 [==============================] - 8s 85us/step - loss: 0.5921 - acc: 0.7470
Epoch 2/30
89442/89442 [==============================] - 7s 82us/step - loss: 0.4941 - acc: 0.7874
Epoch 3/30
89442/89442 [==============================] - 7s 83us/step - loss: 0.4876 - acc: 0.7904
Epoch 4/30
89442/89442 [==============================] - 7s 83us/step - loss: 0.4827 - acc: 0.7936
Epoch 5/30
89442/89442 [==============================] - 7s 83us/step - loss: 0.4785 - acc: 0.7953
Epoch 6/30
89442/89442 [==============================] - 7s 83us/step - loss: 0.4739 - acc: 0.7972
Epoch 7/30
89442/89442 [==============================] - 7s 83us/step - loss: 0.4703 - acc: 0.7994
Epoch 8/30
89442/89442 [==============================] - 7s 83us/step - loss: 0.4664 - acc: 0.8010
Epoch 9/30
89442/89442 [==============================] - 7s 83us/step - loss: 0.4628 - acc: 0.8039
Epoch 10/30
89442/89442 [==============================] - 7s 82us/step - loss: 0.4587 - acc: 0.8049

In [0]:
y_pred = network.predict(X_test)
y_pred = (y_pred > 0.5)
print("{:.3}".format(accuracy_score(y_test, y_pred)))

print(classification_report(y_test,y_pred))

print(confusion_matrix(y_test,y_pred))

0.804
              precision    recall  f1-score   support

           0       0.82      0.77      0.79      1113
           1       0.86      0.79      0.82     11764
           2       0.89      0.89      0.89      7166
           3       0.72      0.76      0.74      9772

   micro avg       0.82      0.80      0.81     29815
   macro avg       0.82      0.80      0.81     29815
weighted avg       0.82      0.80      0.81     29815
 samples avg       0.80      0.80      0.80     29815



/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels.
  'precision', 'predicted', average, warn_for)


ValueError: ignored