In [0]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pickle

In [0]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import SGDClassifier

from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

from sklearn.metrics import roc_curve

In [0]:
import keras
from keras import models
from keras import layers

from keras.utils import to_categorical

Using TensorFlow backend.


In [0]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive


In [0]:
eyes_df = pd.read_csv('/content/drive/My Drive/Colab/thesis/lfwa/lfwa_eyes_dataset.csv')

In [0]:
eyes_df.head(2)

encodings  \
0  [-0.07891007  0.17634775  0.00748135 -0.147872...   
1  [-9.60119069e-03  9.91584584e-02  3.57892364e-...   

                                   file  Brown Eyes  
0  Aaron_Eckhart/Aaron_Eckhart_0001.jpg         0.0  
1      Aaron_Guiel/Aaron_Guiel_0001.jpg         0.0

In [0]:
eyes_df['Brown Eyes'].value_counts()

1.0    8092
0.0    4260
Name: Brown Eyes, dtype: int64

In [0]:
eyes = eyes_df['Brown Eyes'].values.astype(int)

In [0]:
eyes

array([0, 0, 1, ..., 1, 1, 1])

In [0]:
eyes_emb = eyes_df.encodings

eyes_emb = (eyes_emb
 .str.replace('\n','')
 .str.replace('\r','')
 .str.replace('[','')
 .str.replace(']','')
 .str.split())

eyes_emb_lists = eyes_emb.tolist()
eyes_emb_npy = np.asarray(eyes_emb_lists)
eyes_emb_npy = eyes_emb_npy.astype(np.float)

In [0]:
eyes_emb_npy.shape

(12352, 128)

In [0]:
X_train,X_test,y_train,y_test = train_test_split(eyes_emb_npy, eyes,test_size=0.25,random_state=91, stratify=eyes)

print('train')
print(X_train.shape)
print(y_train.shape)

print('test')
print(X_test.shape)
print(y_test.shape)

train
(9264, 128)
(9264,)
test
(3088, 128)
(3088,)


In [0]:
model = SGDClassifier(loss='log', random_state=91, max_iter=40)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print("{:.3}".format(accuracy_score(y_test, y_pred)))

print(classification_report(y_test,y_pred))

print(confusion_matrix(y_test,y_pred))

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If max_iter is set but tol is left unset, the default value for tol in 0.19 and 0.20 will be None (which is equivalent to -infinity, so it has no effect) but will change in 0.21 to 1e-3. Specify tol to silence this warning.
  FutureWarning)


0.706
              precision    recall  f1-score   support

           0       0.57      0.56      0.57      1065
           1       0.77      0.78      0.78      2023

   micro avg       0.71      0.71      0.71      3088
   macro avg       0.67      0.67      0.67      3088
weighted avg       0.70      0.71      0.70      3088

[[ 601  464]
 [ 445 1578]]


In [0]:
model = SGDClassifier(loss='hinge', random_state=91, max_iter=100)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print("{:.3}".format(accuracy_score(y_test, y_pred)))

print(classification_report(y_test,y_pred))

print(confusion_matrix(y_test,y_pred))

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If max_iter is set but tol is left unset, the default value for tol in 0.19 and 0.20 will be None (which is equivalent to -infinity, so it has no effect) but will change in 0.21 to 1e-3. Specify tol to silence this warning.
  FutureWarning)


0.699
              precision    recall  f1-score   support

           0       0.56      0.62      0.59      1065
           1       0.79      0.74      0.76      2023

   micro avg       0.70      0.70      0.70      3088
   macro avg       0.67      0.68      0.67      3088
weighted avg       0.71      0.70      0.70      3088

[[ 657  408]
 [ 522 1501]]


In [0]:


#optimizers.RMSprop(lr=1e-4)

hidden = 100

network = models.Sequential()
network.add(layers.Dense(hidden, use_bias='true', activation='relu', input_shape=(128,)))
network.add(layers.Dense(1, use_bias='true', activation='sigmoid'))

keras.initializers.RandomNormal(mean=0.0, stddev=0.05)

#keras.optimizers.SGD(lr=0.001, momentum=0.0, decay=0.0, nesterov=False)

network.compile(optimizer=keras.optimizers.Adam(lr=0.001, beta_1=0.9, beta_2=0.999, epsilon=None, decay=0.0, amsgrad=False),
                loss='binary_crossentropy',
                metrics=['accuracy'])

network.fit(X_train, y_train, epochs=40, batch_size=30)

Epoch 1/40
9264/9264 [==============================] - 1s 147us/step - loss: 0.5948 - acc: 0.6726
Epoch 2/40
9264/9264 [==============================] - 1s 122us/step - loss: 0.5539 - acc: 0.6999
Epoch 3/40
9264/9264 [==============================] - 1s 136us/step - loss: 0.5475 - acc: 0.7041
Epoch 4/40
9264/9264 [==============================] - 1s 137us/step - loss: 0.5423 - acc: 0.7122
Epoch 5/40
9264/9264 [==============================] - 1s 134us/step - loss: 0.5398 - acc: 0.7152
Epoch 6/40
9264/9264 [==============================] - 1s 131us/step - loss: 0.5368 - acc: 0.7176
Epoch 7/40
9264/9264 [==============================] - 1s 132us/step - loss: 0.5349 - acc: 0.7213
Epoch 8/40
9264/9264 [==============================] - 1s 132us/step - loss: 0.5342 - acc: 0.7229
Epoch 9/40
9264/9264 [==============================] - 1s 134us/step - loss: 0.5307 - acc: 0.7250
Epoch 10/40
9264/9264 [==============================] - 1s 138us/step - loss: 0.5290 - acc: 0.7288
Epoch 11/

In [0]:
y_pred = network.predict(X_test)
y_pred = (y_pred > 0.5)
#score = network.predict_proba(X_test)

print("{:.3}".format(accuracy_score(y_test, y_pred)))
print(classification_report(y_test,y_pred))

print(confusion_matrix(y_test,y_pred))

0.711
              precision    recall  f1-score   support

           0       0.58      0.58      0.58      1065
           1       0.78      0.78      0.78      2023

   micro avg       0.71      0.71      0.71      3088
   macro avg       0.68      0.68      0.68      3088
weighted avg       0.71      0.71      0.71      3088

[[ 620  445]
 [ 446 1577]]


# ethn

In [0]:
ethndf = pd.read_csv('/content/drive/My Drive/Colab/thesis/lfwa/lfwa_ethn_dataset.csv')

In [0]:
ethndf.head(2)

encodings  \
0  [-0.07891007  0.17634775  0.00748135 -0.147872...   
1  [-9.60119069e-03  9.91584584e-02  3.57892364e-...   

                                   file  Asian  White  Black  Indian  score  \
0  Aaron_Eckhart/Aaron_Eckhart_0001.jpg    0.0    1.0    0.0     0.0    100   
1      Aaron_Guiel/Aaron_Guiel_0001.jpg    0.0    1.0    0.0     0.0    100   

  ethnicity  
0     white  
1     white

In [0]:
ethn = ethndf.ethnicity.values

In [0]:
ethn_emb = ethndf.encodings

ethn_emb = (ethn_emb
 .str.replace('\n','')
 .str.replace('\r','')
 .str.replace('[','')
 .str.replace(']','')
 .str.split())

ethn_emb_lists = ethn_emb.tolist()
ethn_emb_npy = np.asarray(ethn_emb_lists)
ethn_emb_npy = ethn_emb_npy.astype(np.float)

In [0]:
X_train,X_test,y_train,y_test = train_test_split(ethn_emb_npy, ethn,test_size=0.25,random_state=91, stratify=ethn)

print('train')
print(X_train.shape)
print(y_train.shape)

print('test')
print(X_test.shape)
print(y_test.shape)

unique, counts = np.unique(y_train, return_counts=True)
print(np.asarray((unique, counts)).T)

train
(7827, 128)
(7827,)
test
(2609, 128)
(2609,)
[['asian' 614]
 ['black' 337]
 ['idnian' 131]
 ['white' 6745]]


In [0]:
model = SGDClassifier(loss='log', random_state=91, max_iter=30)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print("{:.3}".format(accuracy_score(y_test, y_pred)))

print(classification_report(y_test,y_pred))

print(confusion_matrix(y_test,y_pred))

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If max_iter is set but tol is left unset, the default value for tol in 0.19 and 0.20 will be None (which is equivalent to -infinity, so it has no effect) but will change in 0.21 to 1e-3. Specify tol to silence this warning.
  FutureWarning)


0.952
              precision    recall  f1-score   support

       asian       0.89      0.80      0.84       205
       black       0.89      0.84      0.86       112
      idnian       1.00      0.05      0.09        44
       white       0.96      0.99      0.97      2248

   micro avg       0.95      0.95      0.95      2609
   macro avg       0.93      0.67      0.69      2609
weighted avg       0.95      0.95      0.94      2609

[[ 163    2    0   40]
 [   3   94    0   15]
 [   3    1    2   38]
 [  15    9    0 2224]]


In [0]:
model = SGDClassifier(loss='hinge', random_state=91, max_iter=100)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print("{:.3}".format(accuracy_score(y_test, y_pred)))

print(classification_report(y_test,y_pred))

print(confusion_matrix(y_test,y_pred))

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If max_iter is set but tol is left unset, the default value for tol in 0.19 and 0.20 will be None (which is equivalent to -infinity, so it has no effect) but will change in 0.21 to 1e-3. Specify tol to silence this warning.
  FutureWarning)


0.952
              precision    recall  f1-score   support

       asian       0.91      0.79      0.85       205
       black       0.87      0.87      0.87       112
      idnian       0.00      0.00      0.00        44
       white       0.96      0.99      0.97      2248

   micro avg       0.95      0.95      0.95      2609
   macro avg       0.68      0.66      0.67      2609
weighted avg       0.94      0.95      0.94      2609

[[ 162    3    0   40]
 [   2   97    0   13]
 [   3    1    0   40]
 [  11   11    0 2226]]


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [0]:
filename = 'gender_keras_model.sav'
pickle.dump(network, open(filename, 'wb'))

In [0]:
from sklearn.preprocessing import LabelEncoder
# Fit LabelEncoder with our list of classes
label_encoder = LabelEncoder()
#label_encoder.fit(y_train)
label_encoder.fit(ethn)

# Encode class values as integers
#y_train = label_encoder.transform(y_train)
ethn = label_encoder.transform(ethn)

In [0]:
X_train,X_test,y_train,y_test = train_test_split(ethn_emb_npy, ethn,test_size=0.25,random_state=91, stratify=ethn)

print('train')
print(X_train.shape)
print(y_train.shape)

print('test')
print(X_test.shape)
print(y_test.shape)

unique, counts = np.unique(y_train, return_counts=True)
print(np.asarray((unique, counts)).T)

train
(7827, 128)
(7827,)
test
(2609, 128)
(2609,)
[[   0  614]
 [   1  337]
 [   2  131]
 [   3 6745]]


In [0]:
y_train = to_categorical(y_train)
y_test = to_categorical(y_test)


In [0]:

#optimizers.RMSprop(lr=1e-4)

hidden = 100

network = models.Sequential()
network.add(layers.Dense(hidden, use_bias='true', activation='relu', input_shape=(128,)))
network.add(layers.Dense(4, use_bias='true', activation='softmax'))

keras.initializers.RandomNormal(mean=0.0, stddev=0.05)

#keras.optimizers.SGD(lr=0.001, momentum=0.0, decay=0.0, nesterov=False)

network.compile(optimizer=keras.optimizers.Adam(lr=0.001, beta_1=0.9, beta_2=0.999, epsilon=None, decay=0.0, amsgrad=False),
                loss='categorical_crossentropy',
                metrics=['accuracy'])

network.fit(X_train, y_train, epochs=30, batch_size=50, validation_split=0.25)

Train on 5870 samples, validate on 1957 samples
Epoch 1/30
5870/5870 [==============================] - 1s 166us/step - loss: 0.5302 - acc: 0.8463 - val_loss: 0.3914 - val_acc: 0.8498
Epoch 2/30
5870/5870 [==============================] - 0s 78us/step - loss: 0.2839 - acc: 0.9032 - val_loss: 0.2627 - val_acc: 0.9244
Epoch 3/30
5870/5870 [==============================] - 0s 84us/step - loss: 0.2082 - acc: 0.9474 - val_loss: 0.2230 - val_acc: 0.9397
Epoch 4/30
5870/5870 [==============================] - 1s 88us/step - loss: 0.1849 - acc: 0.9514 - val_loss: 0.2060 - val_acc: 0.9433
Epoch 5/30
5870/5870 [==============================] - 1s 94us/step - loss: 0.1760 - acc: 0.9526 - val_loss: 0.1984 - val_acc: 0.9443
Epoch 6/30
5870/5870 [==============================] - 1s 91us/step - loss: 0.1702 - acc: 0.9523 - val_loss: 0.1941 - val_acc: 0.9448
Epoch 7/30
5870/5870 [==============================] - 1s 93us/step - loss: 0.1664 - acc: 0.9532 - val_loss: 0.1932 - val_acc: 0.9438
Epoch 

In [0]:
y_pred = network.predict(X_test)
y_pred = (y_pred > 0.5)
print("{:.3}".format(accuracy_score(y_test, y_pred)))

print(classification_report(y_test,y_pred))

print(confusion_matrix(y_test,y_pred))

0.951
              precision    recall  f1-score   support

           0       0.90      0.82      0.86       205
           1       0.89      0.83      0.86       112
           2       0.57      0.27      0.37        44
           3       0.97      0.98      0.98      2248

   micro avg       0.96      0.95      0.96      2609
   macro avg       0.83      0.73      0.77      2609
weighted avg       0.96      0.95      0.95      2609
 samples avg       0.95      0.95      0.95      2609



/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels.
  'precision', 'predicted', average, warn_for)


ValueError: ignored